server:
  port: 7002
eureka:
  instance:
    hostname: frame-eureka-7002.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://frame-eureka-7001.com:7001/eureka/
